export type CourtType = "oliy" | "jin" | "fuq" | "mam" | "iqt";

export interface CourtEntry {
  name: string;
  address: string;
  phone: string;
  email?: string;
}

export interface RegionEntry { id: string; name: string; }

export const COURT_TYPES: { id: CourtType; name: string; emoji: string }[] = [
  { id: "oliy", name: "Oliy sud",                          emoji: "🏛" },
  { id: "jin",  name: "Jinoyat ishlari bo'yicha sudlar",   emoji: "⚖️" },
  { id: "fuq",  name: "Fuqarolik ishlari bo'yicha sudlar", emoji: "📋" },
  { id: "mam",  name: "Ma'muriy sudlar",                   emoji: "🏢" },
  { id: "iqt",  name: "Iqtisodiy sudlar",                  emoji: "💼" },
];

export const REGIONS: RegionEntry[] = [
  { id: "tashsh",  name: "Toshkent shahar" },
  { id: "tashvil", name: "Toshkent viloyati" },
  { id: "andvil",  name: "Andijon viloyati" },
  { id: "farvil",  name: "Farg'ona viloyati" },
  { id: "namvil",  name: "Namangan viloyati" },
  { id: "samvil",  name: "Samarqand viloyati" },
  { id: "buhvil",  name: "Buxoro viloyati" },
  { id: "navvil",  name: "Navoiy viloyati" },
  { id: "xorvil",  name: "Xorazm viloyati" },
  { id: "qrvil",   name: "Qoraqalpog'iston Respublikasi" },
  { id: "jizzvil", name: "Jizzax viloyati" },
  { id: "sirvil",  name: "Sirdaryo viloyati" },
  { id: "kashvil", name: "Qashqadaryo viloyati" },
  { id: "surxvil", name: "Surxondaryo viloyati" },
];

export const OLIY_SUD: CourtEntry = {
  name: "O'zbekiston Respublikasi Oliy sudi",
  address: "100186, Toshkent sh., Shayxontohur tumani, Abdulla Qodiriy ko'chasi, 1-uy",
  phone: "+998 (71) 239-47-95",
  email: "devonxona.oliy@sud.uz",
};

const JIN: Record<string, CourtEntry[]> = {
  tashsh: [
    { name: "Bektemir tuman sudi",       address: "Toshkent shahar, Bektemir tumani, X.Boyqaro ko'chasi, 9a uy",          phone: "+998 (71) 501-00-82", email: "j.bektemir@sud.uz" },
    { name: "Mirzo Ulug'bek tuman sudi", address: "Toshkent shahar, Sayram 7-tor ko'chasi, 2-uy",                         phone: "+998 (71) 501-00-69", email: "j.m-ulugbek@sud.uz" },
    { name: "Mirobod tuman sudi",        address: "Toshkent shahar, Mirobod tumani, Fidokor ko'chasi, 38-uy",             phone: "+998 (71) 501-00-64", email: "j.mirobod@sud.uz" },
    { name: "Olmazor tuman sudi",        address: "Toshkent shahar, Kichik halqa yo'li ko'chasi, 9-uy",                   phone: "+998 (71) 501-00-37", email: "j.olmazor@sud.uz" },
    { name: "Sergeli tuman sudi",        address: "Toshkent shahar, Sirg'ali tumani, Yangi Sirg'ali ko'chasi",            phone: "+998 (71) 501-00-46", email: "j.sergeli@sud.uz" },
    { name: "Toshkent shahar sudi",      address: "Toshkent shahri, Alisher Navoiy ko'chasi, 23 uy",                     phone: "+998 (71) 501-11-15", email: "j.toshkent@sud.uz" },
    { name: "Uchtepa tuman sudi",        address: "Toshkent shahar, Foziltepa ko'chasi, 42a-uy",                         phone: "+998 (71) 501-00-93", email: "j.uchtepa@sud.uz" },
    { name: "Chilonzor tuman sudi",      address: "Toshkent shahar, Sharq tongi ko'chasi, 1-a",                          phone: "+998 (71) 501-00-45", email: "j.chilonzor@sud.uz" },
    { name: "Shayxontohur tuman sudi",   address: "Toshkent shahar, Shayxontohur tumani, Beruniy 3/4-uy",                phone: "+998 (71) 501-00-31", email: "j.shayxontoxur@sud.uz" },
    { name: "Yunusobod tuman sudi",      address: "Toshkent shahar, A.Temur ko'chasi, 133-uy",                           phone: "+998 (71) 501-00-59", email: "j.yunusobod@sud.uz" },
    { name: "Yakkasaroy tuman sudi",     address: "Toshkent shahar, Shota Rustaveli ko'chasi, 62-uy",                    phone: "+998 (71) 501-00-86", email: "j.yakkasaroy@sud.uz" },
    { name: "Yangihayot tuman sudi",     address: "Toshkent shahar, Yangihayot tumani, Lutflkor ko'chasi, 33-uy",        phone: "+998 (71) 501-06-03", email: "j.yangihayot@sud.uz" },
    { name: "Yashnobod tuman sudi",      address: "Toshkent shahar, Yashnobod tumani, Taraqqiyot 1-berk ko'chasi, 8-uy", phone: "+998 (71) 501-00-43", email: "j.yashnobod@sud.uz" },
  ],
  tashvil: [
    { name: "Toshkent viloyat sudi",     address: "Toshkent shahar, Yakkasaroy tumani, Sh.Rustaveli ko'chasi, 93-uy",    phone: "+998 (55) 510-74-74", email: "j.toshkent.v@sud.uz" },
    { name: "Yangiyo'l shahar sudi",     address: "Toshkent viloyati, Yangyo'l shahar, Ibn-Sino ko'chasi, 20-uy",        phone: "+998 (55) 517-02-75", email: "j.yangiyul@sud.uz" },
    { name: "Chirchiq shahar sudi",      address: "Toshkent viloyati, Chirchiq shahar, A.Navoiy ko'chasi, 139-uy",       phone: "+998 (55) 517-02-70", email: "j.chirchiq@sud.uz" },
    { name: "Ohangaron shahar sudi",     address: "Toshkent viloyati, Ohangaron shahar, Ezgulik ko'chasi, 100-uy",       phone: "+998 (55) 517-02-73", email: "j.oxangoron.sh@sud.uz" },
    { name: "Olmaliq shahar sudi",       address: "Toshkent viloyati, Olmaiq shahar, Ramazonov ko'chasi, 14A-uy",        phone: "+998 (55) 517-02-59", email: "j.olmalig@sud.uz" },
    { name: "Angren shahar sudi",        address: "Toshkent viloyati, Angren shahar, Bunyodkor ko'chasi, 1-uy",          phone: "+998 (55) 517-02-35", email: "j.angren@sud.uz" },
    { name: "Bekobod shahar sudi",       address: "Toshkent viloyati, Bekobod shahar, Istiqlol ko'chasi, 15-uy",         phone: "+998 (55) 517-42-42", email: "j.bekobod@sud.uz" },
    { name: "Nurafshon shahar sudi",     address: "Toshkent viloyati, Nurafshon shahar, Toshkent-yo'li ko'chasi, 240-uy",phone: "+998 (55) 517-02-56", email: "j.nurafshon@sud.uz" },
    { name: "Parkent tuman sudi",        address: "Toshkent viloyati, Parkent tumani, Kumushkon ko'chasi, 5-uy",         phone: "+998 (55) 517-02-76", email: "j.parkent@sud.uz" },
    { name: "Qibray tuman sudi",         address: "Toshkent viloyati, Qibray tumani, Zebiniso ko'chasi, 10-uy",         phone: "+998 (55) 517-02-53", email: "j.qibray@sud.uz" },
    { name: "Bo'stonliq tuman sudi",     address: "Toshkent viloyati, Bo'stonliq tumani, Fazalkent sh., Lutifiy ko'chasi, 1-uy", phone: "+998 (55) 517-02-36", email: "j.bustonliq@sud.uz" },
    { name: "Zangiota tuman sudi",       address: "Toshkent viloyati, Zangiota tumani, Eshonguzar q., Mustaqillik ko'chasi, 20-uy", phone: "+998 (55) 517-02-37", email: "j.zangiota@sud.uz" },
    { name: "Pskent tuman sudi",         address: "Toshkent viloyati, Pskent tumani, M.Malikov ko'chasi, 1-uy",          phone: "+998 (55) 517-02-78", email: "j.pskent@sud.uz" },
  ],
  andvil: [
    { name: "Andijon viloyat sudi",     address: "Andijon shahar, Alisher Navoiy shoh ko'chasi, 15-uy",        phone: "+998 (74) 224-42-44", email: "j.andijon@sud.uz" },
    { name: "Andijon shahar sudi",      address: "Andijon shahar, Toshkent ko'chasi, 4-uy",                    phone: "+998 (74) 224-07-37", email: "j.andijon.sh@sud.uz" },
    { name: "Andijon tuman sudi",       address: "Andijon tumani, Sanoat MFY, Oltin vodiy ko'chasi 4-uy",      phone: "+998 (74) 224-07-67", email: "j.andijon.t@sud.uz" },
    { name: "Asaka tuman sudi",         address: "Asaka tumani, Sohil bo'yi ko'chasi 11-uy",                   phone: "+998 (74) 224-07-87", email: "j.asaka@sud.uz" },
    { name: "Baliqchi tuman sudi",      address: "Baliqchi tuman, Andijon ko'chasi, 1-uy",                     phone: "+998 (74) 224-07-97", email: "j.baliqchi@sud.uz" },
    { name: "Jalaquduq tuman sudi",     address: "Jalaquduq tumani, Tuyalas MFY, Mashriq ko'chasi, 2-uy",      phone: "+998 (74) 224-17-67", email: "j.jalaquduq@sud.uz" },
    { name: "Izboskan tuman sudi",      address: "Izboskan tuman, J.Siddikov ko'chasi 3-uy",                   phone: "+998 (74) 224-17-87", email: "j.izboskan@sud.uz" },
    { name: "Qo'rg'ontepa tuman sudi", address: "Qo'rg'ontepa tuman, Mustaqillik ko'chasi, 50-uy",            phone: "+998 (74) 224-17-97", email: "j.qurgontepa@sud.uz" },
    { name: "Marhamat tuman sudi",      address: "Marhamat tumani, Mustaqillik ko'chasi 33-uy",                phone: "+998 (74) 224-27-07", email: "j.marxamat@sud.uz" },
    { name: "Oltinko'l tuman sudi",    address: "Oltinko'l tuman, Chinobod shox ko'chasi, 15-uy",             phone: "+998 (74) 224-27-17", email: "j.oltinkul@sud.uz" },
    { name: "Shahrixon tuman sudi",    address: "Shahrixon tuman, R.Yodgorov ko'chasi, 3-uy",                 phone: "+998 (74) 224-27-87", email: "j.shahrixon@sud.uz" },
    { name: "Xonobod shahar sudi",     address: "Xonobod shahar, Bog'ibaland ko'chasi, 1-uy",                 phone: "+998 (74) 224-27-57", email: "j.xonobod@sud.uz" },
    { name: "Xo'jaobod tuman sudi",    address: "Xo'jaobod tuman, Uzun ko'chasi 2-uy",                        phone: "+998 (74) 224-27-67", email: "j.xujaobod@sud.uz" },
    { name: "Ulug'nor tuman sudi",     address: "Ulug'nor tumani, Mustaqillik ko'chasi, 3-uy",                phone: "+998 (74) 224-47-27", email: "j.ulugnor@sud.uz" },
  ],
  farvil: [
    { name: "Farg'ona viloyat sudi",   address: "Farg'ona shahar, Sohibqiron Temur ko'chasi, 30-uy",          phone: "+998 (73) 249-01-01", email: "j.fargona@sud.uz" },
    { name: "Farg'ona shahar sudi",    address: "Farg'ona shahar, Yuksalish ko'chasi, 103-uy",                phone: "+998 (73) 249-15-01", email: "j.fargona.sh@sud.uz" },
    { name: "Farg'ona tuman sudi",     address: "Farg'ona tumani, Vodil shaharchasi, Buloqboshi ko'chasi",    phone: "+998 (73) 249-15-02", email: "j.fargona.t@sud.uz" },
    { name: "Qo'qon shahar sudi",      address: "Qo'qon shahar, I.Buhariy ko'chasi, 37-uy",                  phone: "+998 (73) 249-15-03", email: "j.quqon@sud.uz" },
    { name: "Marg'ilon shahar sudi",   address: "Marg'ilon shahar, Nurafshon ko'chasi, 9-uy",                phone: "+998 (73) 249-15-13", email: "j.margulon@sud.uz" },
    { name: "Quvasoy shahar sudi",     address: "Quvasoy shahar, Mustaqillik ko'chasi, 95-uy",               phone: "+998 (73) 249-70-71", email: "j.quvasoy@sud.uz" },
    { name: "Beshariq tuman sudi",     address: "Beshariq tumani, Oltin Vodiy ko'chasi, 101-uy",             phone: "+998 (73) 249-15-06", email: "j.beshariq@sud.uz" },
    { name: "Buvayda tuman sudi",      address: "Buvayda tumani, Yangi qo'rg'on sh., Bog'eram ko'chasi, 56-uy", phone: "+998 (73) 249-15-08", email: "j.buvayda@sud.uz" },
    { name: "Dang'ara tuman sudi",     address: "Dang'ara tumani, Muqumiy ko'chasi, 2-uy",                   phone: "+998 (73) 249-15-09", email: "j.dangara@sud.uz" },
    { name: "Oltiariq tuman sudi",     address: "Oltiariq tumani, O'zbekiston ko'chasi, 28-uy",              phone: "+998 (73) 249-15-14", email: "j.oltiariq@sud.uz" },
    { name: "Rishton tuman sudi",      address: "Rishton tumani, Roshidoniya ko'chasi, 187A-uy",             phone: "+998 (73) 249-15-15", email: "j.rishton@sud.uz" },
    { name: "Toshloq tuman sudi",      address: "Toshloq tumani, Dovon ko'chasi, 93-uy",                     phone: "+998 (73) 249-15-17", email: "j.toshloq@sud.uz" },
    { name: "Uchko'prik tuman sudi",   address: "Uchko'prik tumani, X.Olimjon ko'chasi, 80-uy",              phone: "+998 (73) 249-15-18", email: "j.uchkuprik@sud.uz" },
    { name: "Quva tuman sudi",         address: "Quva tumani, Qayqubbot ko'chasi, 184-uy",                   phone: "+998 (73) 249-15-11", email: "j.quva@sud.uz" },
  ],
  namvil: [
    { name: "Namangan viloyat sudi",     address: "Namangan shahri, N. Namangoniy ko'chasi, 10 uy",            phone: "+998 (69) 211-17-77", email: "j.namangan@sud.uz" },
    { name: "Namangan shahar sudi",      address: "Namangan shahar, N.Nomongoniy ko'chasi, 10-uy",             phone: "+998 (69) 211-10-36", email: "j.namangan.sh@sud.uz" },
    { name: "Namangan tuman sudi",       address: "Namangan tumani, Toshbuloq sh., N.Oxunov ko'chasi, 3-uy",  phone: "+998 (69) 211-10-98", email: "j.namangan.t@sud.uz" },
    { name: "Chust tuman sudi",          address: "Chust shahar, Karamsada MFY, Charag'on ko'chasi, 74-uy",   phone: "+998 (69) 211-10-95", email: "j.chust@sud.uz" },
    { name: "Chortoq tuman sudi",        address: "Chortoq tumani, Mustaqillik shox ko'chasi, 4 uy",          phone: "+998 (69) 211-10-86", email: "j.chortoq@sud.uz" },
    { name: "Uchqo'rg'on tuman sudi",   address: "Uchqo'rg'on tumani, Lutfiy ko'chasi, 2 uy",                phone: "+998 (69) 211-10-69", email: "j.uchqurgon@sud.uz" },
    { name: "To'raqo'rg'on tuman sudi", address: "To'raqo'rg'on shahri, Al-Fargoniy ko'chasi, 2-uy",         phone: "+998 (69) 211-10-59", email: "j.turaqurgon@sud.uz" },
    { name: "Pop tuman sudi",            address: "Pop shahar, E.Yondosh ko'chasi, 7-uy",                     phone: "+998 (69) 211-10-53", email: "j.pop@sud.uz" },
    { name: "Norin tuman sudi",          address: "Norin tumani, Xaqulobod shahri, Beruniy ko'chasi, 21 uy",  phone: "+998 (69) 211-10-39", email: "j.norin@sud.uz" },
    { name: "Kosonsoy tuman sudi",       address: "Kosonsoy shahar, Gulobod ko'chasi, 11-uy",                 phone: "+998 (69) 211-10-81", email: "j.kosonsoy@sud.uz" },
    { name: "Mingbuloq tuman sudi",      address: "Mingbuloq tumani, Jomasho'y sh., Ozodlik ko'chasi",        phone: "+998 (69) 211-12-55", email: "j.mingbuloq@sud.uz" },
    { name: "Yangiqo'rg'on tuman sudi", address: "Yangiqo'rg'on tumani",                                      phone: "+998 (69) 211-11-09", email: "j.yangiqurgon@sud.uz" },
  ],
  samvil: [
    { name: "Samarqand viloyat sudi",   address: "Samarqand shahar, Mingtut ko'chasi 1-uy",                   phone: "+998 (55) 706-70-05", email: "j.samarqand@sud.uz" },
    { name: "Samarqand shahar sudi",    address: "Samarqand shahri, Bernuiy ko'chasi 65-uy",                  phone: "+998 (55) 706-70-07", email: "j.samarqand.sh@sud.uz" },
    { name: "Samarqand tuman sudi",     address: "Samarqand tuman, Xo'ja Axror Vali-1 mahallasi",            phone: "+998 (55) 706-70-24", email: "j.samarqand.t@sud.uz" },
    { name: "Urgut tuman sudi",         address: "Urgut tuman, Urgut shahri, Qoratera ko'chasi",              phone: "+998 (55) 706-70-26", email: "j.urgut@sud.uz" },
    { name: "Kattaqo'rg'on shahar sudi",address: "Kattaqo'rg'on shahar, A.Navoiy ko'chasi 105-uy",           phone: "+998 (55) 706-70-14", email: "j.kattaqurgon@sud.uz" },
    { name: "Kattaqo'rg'on tuman sudi", address: "Kattaqo'rg'on tumani, Mustaqillik ko'chasi, 37-uy",        phone: "+998 (55) 706-70-13", email: "j.kattaqurgon.t@sud.uz" },
    { name: "Ishtixon tuman sudi",      address: "Ishtixon shahri, Ishtixon ko'chasi, 11-uy",                phone: "+998 (55) 706-70-12", email: "j.ishtixon@sud.uz" },
    { name: "Jomboy tuman sudi",        address: "Jomboy shahri, Galakapa ko'chasi, 15-uy",                  phone: "+998 (55) 706-70-11", email: "j.jomboy@sud.uz" },
    { name: "Bulung'ur tuman sudi",     address: "Bulung'ur tumani, do'slik ko'chasi, 24-uy",                phone: "+998 (55) 706-70-09", email: "j.bulungur@sud.uz" },
    { name: "Pastdarg'om tuman sudi",   address: "Pastdarg'om tumani, Juma shahri, A.Temur ko'chasi",        phone: "+998 (55) 706-70-22", email: "j.pastdargom@sud.uz" },
    { name: "Paxtachi tuman sudi",      address: "Paxtachi tuman, Ziyovuddin sh., Mustaqillik ko'chasi, 48-uy", phone: "+998 (55) 706-70-23", email: "j.paxtachi@sud.uz" },
    { name: "Tayloq tuman sudi",        address: "Tayloq tumani, Mustaqillik ko'chasi, 8-uy",                phone: "+998 (55) 706-70-25", email: "j.tayloq@sud.uz" },
    { name: "Payariq tuman sudi",       address: "Payariq tuman, Chelak shahri, Istiqlol ko'chasi, 59-uy",   phone: "+998 (55) 706-70-21", email: "j.payariq@sud.uz" },
  ],
  buhvil: [
    { name: "Buxoro viloyat sudi",     address: "Buxoro shahar, Hofiz Tonish Buxoriy ko'chasi, 13-uy",       phone: "+998 (65) 220-01-14", email: "j.buxoro@sud.uz" },
    { name: "Buxoro shahar sudi",      address: "Buxoro shahar, I.Mo'minov ko'chasi, 28-uy",                 phone: "+998 (65) 220-02-24", email: "j.buxoro.sh@sud.uz" },
    { name: "Buxoro tuman sudi",       address: "Buxoro tumani, Bahor ko'chasi, 25-uy",                      phone: "+998 (65) 220-02-27", email: "j.buxoro.t@sud.uz" },
    { name: "G'ijduvon tuman sudi",    address: "G'ijduvon shahar, Mustaqillik ko'chasi, 2-uy",              phone: "+998 (65) 220-05-69", email: "j.gijduvon@sud.uz" },
    { name: "Kogon shahar sudi",       address: "Kogon shahar, Qorovulbozor shoh ko'chasi, 2-uy",            phone: "+998 (65) 220-02-81", email: "j.kogon@sud.uz" },
    { name: "Vobkent tuman sudi",      address: "Vobkent shahri, F.Xo'jaev ko'chasi, 21-uy",                phone: "+998 (65) 220-05-51", email: "j.vobkent@sud.uz" },
    { name: "Romitan tuman sudi",      address: "Romitan shahar, A.Temur ko'chasi, 44-uy",                   phone: "+998 (65) 220-05-81", email: "j.romitan@sud.uz" },
    { name: "Qorako'l tuman sudi",     address: "Qorako'l shahri, Toshkent ko'chasi, 28-uy",                phone: "+998 (65) 220-05-72", email: "j.qorakul@sud.uz" },
    { name: "Peshku tuman sudi",       address: "Peshku tumani, A.Temur ko'chasi, 5-uy",                     phone: "+998 (65) 220-06-16", email: "j.peshku@sud.uz" },
    { name: "Shofirkon tuman sudi",    address: "Shofirkon tumani, Sultonobod ko'chasi, 3-uy",               phone: "+998 (65) 220-05-84", email: "j.shofirkon@sud.uz" },
    { name: "Jondor tuman sudi",       address: "Jondor tuman, M.Tarobiy ko'chasi, 2-uy",                   phone: "+998 (65) 220-07-38", email: "j.jondor@sud.uz" },
    { name: "Olot tuman sudi",         address: "Olot shahar, Olot ko'chasi, 147-uy",                        phone: "+998 (65) 220-05-79", email: "j.olot@sud.uz" },
  ],
  navvil: [
    { name: "Navoiy viloyat sudi",     address: "Navoiy shahar, O'zbekiston ko'chasi, 11A-uy",               phone: "+998 (79) 222-01-24", email: "j.navoiy@sud.uz" },
    { name: "Navoiy shahar sudi",      address: "Navoiy shahar, O'zbekiston ko'chasi, 14-uy",               phone: "+998 (79) 222-01-16", email: "j.navoiy.sh@sud.uz" },
    { name: "Zarafshon shahar sudi",   address: "Zarafshon shahar, Marvarid ko'chasi, 1-uy",                 phone: "+998 (79) 222-01-59", email: "j.zarafshon@sud.uz" },
    { name: "Nurota tuman sudi",       address: "Nurota tuman, X.Xudoyqulov ko'chasi, 49-uy",               phone: "+998 (79) 222-01-16", email: "j.nurota@sud.uz" },
    { name: "Navbahor tuman sudi",     address: "Navbahor tuman, Boburshox ko'chasi, 4-uy",                  phone: "+998 (79) 222-02-46", email: "j.navbahor@sud.uz" },
    { name: "Qiziltepa tuman sudi",    address: "Qiziltepa tuman, O'zbekiston ko'chasi, 19-uy",             phone: "+998 (79) 222-02-45", email: "j.qiziltepa@sud.uz" },
    { name: "Karmana tuman sudi",      address: "Karmana tuman, Temur malik ko'chasi, 16-uy",               phone: "+998 (79) 222-01-18", email: "j.karmana@sud.uz" },
    { name: "Xatirchi tuman sudi",     address: "Xatirchi tuman, Pulkan ko'chasi, 60-uy",                   phone: "+998 (79) 222-02-36", email: "j.xatirchi@sud.uz" },
    { name: "Uchquduq tuman sudi",     address: "Uchquduq tuman, Navruz ko'chasi, 30-uy",                   phone: "+998 (79) 222-01-12", email: "j.uchquduq@sud.uz" },
    { name: "Tomdi tuman sudi",        address: "Tomdi tuman, Bazar Jirau ko'chasi, 4-uy",                  phone: "+998 (79) 222-01-40", email: "j.tomdi@sud.uz" },
    { name: "Konimex tuman sudi",      address: "Konimex tuman, Bunyodkor ko'chasi, 19-uy",                 phone: "+998 (79) 222-01-13", email: "j.konimex@sud.uz" },
  ],
  xorvil: [
    { name: "Xorazm viloyat sudi",     address: "Urganch shahri, Tinchlik ko'chasi, 22-uy",                  phone: "+998 (62) 227-79-77", email: "j.xorazm@sud.uz" },
    { name: "Urganch shahar sudi",     address: "Urganch shahri, Sheroziy ko'chasi, 14-uy",                  phone: "+998 (62) 227-77-61", email: "j.urganch@sud.uz" },
    { name: "Xiva shahar sudi",        address: "Xiva shahar, A.Temur ko'chasi, 3-uy",                       phone: "+998 (62) 227-77-62", email: "j.xiva.sh@sud.uz" },
    { name: "Xiva tuman sudi",         address: "Xiva tumani, A.Temur ko'chasi, 3-uy",                       phone: "+998 (62) 227-77-84", email: "j.xiva.t@sud.uz" },
    { name: "Gurlan tuman sudi",       address: "Gurlan tumani, P.Mahmud ko'chasi, 26-uy",                   phone: "+998 (62) 227-77-81", email: "j.gurlan@sud.uz" },
    { name: "Shovot tuman sudi",       address: "Shovot tumani, Turkiston ko'chasi, 77-uy",                  phone: "+998 (62) 227-77-82", email: "j.shovot@sud.uz" },
    { name: "Xonqa tuman sudi",        address: "Xonqa tumani, M.Abdullayev ko'chasi, 2-uy",                 phone: "+998 (62) 227-77-68", email: "j.xonqa@sud.uz" },
    { name: "Yangibozor tuman sudi",   address: "Yangibozor tumani, J.Manguberdiy ko'chasi, 46-uy",          phone: "+998 (62) 227-77-64", email: "j.yangibozor@sud.uz" },
    { name: "Xazorasp tuman sudi",     address: "Xazorasp tumani, Mustaqillik ko'chasi, 44-uy",              phone: "+998 (62) 227-77-65", email: "j.xazorasp@sud.uz" },
    { name: "Qo'shko'pir tuman sudi",  address: "Qo'shko'pir tumani, Mustaqillik ko'chasi",                  phone: "+998 (62) 227-77-80", email: "j.qushkupir@sud.uz" },
    { name: "Bog'ot tuman sudi",       address: "Bog'ot tumani, Baynalmilalchi ko'chasi, 1-uy",              phone: "+998 (62) 227-77-69", email: "j.bogot@sud.uz" },
    { name: "Tuproqqal'a tuman sudi",  address: "Pitnaq shahar, Mustaqillik ko'chasi, 1-uy",                 phone: "+998 (62) 227-77-60", email: "j.tuproqqala@sud.uz" },
  ],
  qrvil: [
    { name: "Qoraqalpog'iston Respublikasi sudi", address: "Nukus shahar, I.Karimov ko'chasi, 122-uy",    phone: "+998 (55) 102-40-42", email: "j.qr@sud.uz" },
    { name: "Nukus shahar sudi",                   address: "Nukus shahar, E.Olakuz ko'chasi, 173/1-uy",   phone: "+998 (55) 102-40-25", email: "j.nukus@sud.uz" },
    { name: "Nukus tuman sudi",                    address: "Nukus tuman, Darsan ko'chasi, 25-uy",         phone: "+998 (55) 102-40-51", email: "j.nukus.t@sud.uz" },
    { name: "To'rtko'l tuman sudi",                address: "Turtkul tuman, Turtkul ko'chasi, 62-uy",       phone: "+998 (55) 102-40-26", email: "j.turtkul@sud.uz" },
    { name: "Qo'ng'irot tuman sudi",               address: "Qungirot tuman, O'zbekiston ko'chasi, 77A uy",phone: "+998 (55) 102-40-38", email: "j.qungirot@sud.uz" },
    { name: "Chimboy tuman sudi",                  address: "Chimboy tumani, Do'stlik guzari ko'chasi",     phone: "+998 (55) 102-40-54", email: "j.chimboy@sud.uz" },
    { name: "Ellikqal'a tuman sudi",               address: "Ellikqal'a tuman, Bo'ston shahri, Al-Beruniy ko'chasi, 10-uy", phone: "+998 (55) 102-40-28", email: "j.ellikqala@sud.uz" },
    { name: "Beruniy tuman sudi",                  address: "Beruniy tuman, Beruniy shahri, Kat ko'chasi",   phone: "+998 (55) 102-40-31", email: "j.beruniy@sud.uz" },
    { name: "Xo'jayli tuman sudi",                 address: "Xujayli tuman, Dustlik ko'chasi",               phone: "+998 (55) 102-40-33", email: "j.xujayli@sud.uz" },
    { name: "Amudaryo tuman sudi",                 address: "Amudaryo tumani, Mang'it shahar, Gurlan ko'chasi", phone: "+998 (55) 102-40-32", email: "j.amudaryo@sud.uz" },
    { name: "Taxiatosh tuman sudi",                address: "Taxiatosh tumani, Sh.Rashidov ko'chasi, 16-uy", phone: "+998 (55) 102-40-61", email: "j.taxiatosh@sud.uz" },
    { name: "Kegeyli tuman sudi",                  address: "Kegeyli tuman, Dustlik ko'chasi",               phone: "+998 (55) 102-40-52", email: "j.kegeyli@sud.uz" },
    { name: "Mo'ynoq tuman sudi",                  address: "Muynoq tuman, Ajiniyaz ko'chasi, 72-uy",        phone: "+998 (55) 102-40-46", email: "j.muynoq@sud.uz" },
  ],
  jizzvil: [
    { name: "Jizzax viloyat sudi",     address: "Jizzax shahri, Sayiljoyi ko'chasi, 63-uy",                 phone: "+998 (72) 152-05-70", email: "j.jizzah@sud.uz" },
    { name: "Jizzax shahar sudi",      address: "Jizzax shahri, O.Azimov ko'chasi, 7-uy",                   phone: "+998 (72) 152-05-59", email: "j.jizzah.sh@sud.uz" },
    { name: "G'allaorol tuman sudi",   address: "G'allaorol tumani, Sarbozor qo'rgoni",                     phone: "+998 (72) 152-05-99", email: "j.gallaorol@sud.uz" },
    { name: "Arnasoy tuman sudi",      address: "Arnasoy tumani, g'oliblar ShFY, Alpomish ko'chasi, 60-uy", phone: "+998 (72) 152-06-75", email: "j.arnasoy@sud.uz" },
    { name: "Baxmal tuman sudi",       address: "Baxmal tumani, o'smat shaharchasi, Mustaqillik ko'chasi, 1-uy", phone: "+998 (72) 152-05-89", email: "j.baxmal@sud.uz" },
    { name: "Do'stlik tuman sudi",     address: "Do'stlik shaharchasi, Do'stlik ko'chasi, 15-uy",           phone: "+998 (72) 152-05-61", email: "j.dustlik@sud.uz" },
    { name: "Zafarobod tuman sudi",    address: "Zafarobod tumani, A.Navoy ko'chasi, 1-uy",                 phone: "+998 (72) 152-05-62", email: "j.zafarobod@sud.uz" },
    { name: "Zarbdor tuman sudi",      address: "Zarbdor tumani, Mustaqillik shoh ko'chasi",                phone: "+998 (72) 152-05-63", email: "j.zarbdor@sud.uz" },
    { name: "Zomin tuman sudi",        address: "Zomin shahar, A.Sattarov ko'chasi, 1-uy",                  phone: "+998 (72) 152-05-79", email: "j.zomin@sud.uz" },
    { name: "Paxtakor tuman sudi",     address: "Paxtakor shahri, Y.Rajabiy ko'chasi, 1-uy",                phone: "+998 (72) 152-05-64", email: "j.paxtakor@sud.uz" },
    { name: "Forish tuman sudi",       address: "Forish tumani, Bog'don shaharchasi, Fayzobod ko'chasi",    phone: "+998 (72) 152-05-67", email: "j.forish@sud.uz" },
    { name: "Mirzacho'l tuman sudi",   address: "Mirzacho'l tumani, Gagarin shahri, Gagarin ko'chasi, 7-uy",phone: "+998 (72) 152-05-29", email: "j.mirzachul@sud.uz" },
    { name: "Sh.Rashidov tuman sudi",  address: "Sh.Rashidov tumani, Uchter daxasi, Paxtakor ko'chasi",    phone: "+998 (72) 152-05-19", email: "j.jizzah.t@sud.uz" },
    { name: "Yangiobod tuman sudi",    address: "Yangiobod shaharchasi, Mustaqillik ko'chasi, 4-uy",        phone: "+998 (72) 152-06-23", email: "j.yangiobod@sud.uz" },
  ],
  sirvil: [
    { name: "Sirdaryo viloyat sudi",   address: "Guliston shahar, Navoiy shox ko'chasi, 47-uy",              phone: "+998 (67) 651-75-75", email: "j.sirdaryo@sud.uz" },
    { name: "Guliston tuman sudi",     address: "Guliston tumani, Dehqonobod sh., Turkiston ko'chasi, 26-uy",phone: "+998 (67) 651-35-44", email: "j.guliston.t@sud.uz" },
    { name: "Boyovut tuman sudi",      address: "Boyovut tumani, Boyovut sh., Tinlik ko'chasi, 26-uy",       phone: "+998 (67) 651-35-45", email: "j.boyovut@sud.uz" },
    { name: "Mirzaobod tuman sudi",    address: "Mirzaobod tumani, Navro'z sh., Mustaqillik ko'chasi, 5-uy", phone: "+998 (67) 651-35-47", email: "j.mirzabod@sud.uz" },
    { name: "Oqoltin tuman sudi",      address: "Oqoltin tumani, Sardoba sh., Islomobod ko'chasi, 7-uy",     phone: "+998 (67) 651-35-46", email: "j.oqoltin@sud.uz" },
    { name: "Sayhunobod tuman sudi",   address: "Sayhunobod tumani, Sayhun sh., Navoiy ko'chasi, 10-uy",     phone: "+998 (67) 651-35-48", email: "j.sayxunobod@sud.uz" },
    { name: "Sardoba tuman sudi",      address: "Sardoba tumani, Paxtaobod sh., Oyoq ko'chasi, 9-uy",        phone: "+998 (67) 651-35-56", email: "j.sardoba@sud.uz" },
    { name: "Sirdaryo tuman sudi",     address: "Sirdaryo tumani, Sirdaryo shahri, O'zbekiston ko'chasi, 80-uy", phone: "+998 (67) 651-35-34", email: "j.sirdaryo.t@sud.uz" },
    { name: "Shirin shahar sudi",      address: "Shirin shahri, A.Temur ko'chasi, 12-uy",                    phone: "+998 (67) 651-35-43", email: "j.shirin@sud.uz" },
    { name: "Yangiyer shahar sudi",    address: "Yangier shahri, Quruvchilar ko'chasi, 9-uy",                phone: "+998 (67) 651-35-41", email: "j.yangiyer@sud.uz" },
    { name: "Xovos tuman sudi",        address: "Hovos tumani, Bunyodkor mahallas, Samarqand ko'chasi",       phone: "+998 (67) 651-35-42", email: "j.xovos@sud.uz" },
  ],
  kashvil: [
    { name: "Qashqadaryo viloyat sudi",address: "Qarshi shahar, Nurbog' ko'chasi, 97-uy",                   phone: "+998 (75) 404-69-11", email: "j.qashqadaryo@sud.uz" },
    { name: "Qarshi shahar sudi",      address: "Qarshi shahar, Nurbog' ko'chasi, 41-uy",                   phone: "+998 (75) 404-69-12", email: "j.qarshi@sud.uz" },
    { name: "Qarshi tuman sudi",       address: "Qarshi tuman, Beshket shahri, Mustaqillik ko'chasi, 18-uy", phone: "+998 (75) 404-69-13", email: "j.qarshi.t@sud.uz" },
    { name: "Shahrisabz shahar sudi",  address: "Shahrisabz shahar, Ipak yo'li ko'chasi, 158-uy",           phone: "+998 (75) 404-69-16", email: "j.shaxrisabz@sud.uz" },
    { name: "G'uzor tuman sudi",       address: "G'uzor tuman, O'zbekiston ko'chasi, 72-uy",               phone: "+998 (75) 404-69-18", email: "j.guzor@sud.uz" },
    { name: "Qamashi tuman sudi",      address: "Qamashi tuman, Istiqlol ko'chasi, 47-uy",                  phone: "+998 (75) 404-69-20", email: "j.qamashi@sud.uz" },
    { name: "Dehqonobod tuman sudi",   address: "Dehqonobod tuman, M.Ulug'bek ko'chasi, 3-uy",             phone: "+998 (75) 404-69-21", email: "j.dexqonobod@sud.uz" },
    { name: "Kitob tuman sudi",        address: "Kitob tuman, Katta yo'l ko'chasi",                         phone: "+998 (75) 404-69-24", email: "j.kitob@sud.uz" },
    { name: "Muborak tuman sudi",      address: "Muborak tuman, Zanjirsoy shoh ko'chasi, 2/1-uy",           phone: "+998 (75) 404-69-29", email: "j.muborak@sud.uz" },
    { name: "Chiroqchi tuman sudi",    address: "Chiroqchi tuman, Mustaqillik ko'chasi, 7-uy",              phone: "+998 (75) 404-69-31", email: "j.chiroqchi@sud.uz" },
    { name: "Yakkabog' tuman sudi",    address: "Yakkabog' tuman, Sahovat ko'chasi, 1-uy",                 phone: "+998 (75) 404-69-32", email: "j.yakkabog@sud.uz" },
    { name: "Mirishkor tuman sudi",    address: "Mirishkor tuman, Mustaqillik ko'chasi, 14-uy",             phone: "+998 (75) 404-69-28", email: "j.mirishkor@sud.uz" },
    { name: "Nishon tuman sudi",       address: "Nishon tuman, Yangi Nishon shahri, O'zbekiston ko'chasi, 22-uy", phone: "+998 (75) 404-69-30", email: "j.nishon@sud.uz" },
    { name: "Ko'kdala tuman sudi",     address: "Ko'kdala tuman, Ettitom shaharchasi, Nurafshon ko'chasi, 51-uy", phone: "+998 (75) 404-69-27", email: "j.kokdala@sud.uz" },
  ],
  surxvil: [
    { name: "Surxondaryo viloyat sudi",address: "Termiz shahri, Islom Karimov ko'chasi, 40-uy",             phone: "+998 (76) 228-19-00", email: "j.surxondaryo@sud.uz" },
    { name: "Termiz shahar sudi",      address: "Termiz shahar, Iso At Termiziy ko'chasi, 5-A uy",          phone: "+998 (76) 228-19-01", email: "j.termiz@sud.uz" },
    { name: "Termiz tuman sudi",       address: "Termiz tumani, At-Termiziy ko'chasi, 3-uy",                phone: "+998 (76) 228-30-02", email: "j.termiz.t@sud.uz" },
    { name: "Denov tuman sudi",        address: "Denov tuman, Qo'zichoqli mahallasi, Eski bog' ko'chasi 111-uy", phone: "+998 (76) 228-19-05", email: "j.denov@sud.uz" },
    { name: "Jarqo'rg'on tuman sudi",  address: "Jarqo'rg'on tumani, Y. Ohunboboyev ko'chasi, 1-uy",       phone: "+998 (76) 228-19-06", email: "j.jarqurgon@sud.uz" },
    { name: "Qiziriq tuman sudi",      address: "Qiziriq tumani, Ibn Sino ko'chasi, 3-uy",                  phone: "+998 (76) 228-19-07", email: "j.qiziriq@sud.uz" },
    { name: "Qumqo'rg'on tuman sudi",  address: "Qumqo'rg'on tumani, O'zbekiston ko'chasi, 22-uy",        phone: "+998 (76) 228-19-08", email: "j.qumqurgon@sud.uz" },
    { name: "Muzrabot tuman sudi",     address: "Muzrabot tumani, Quyoshkent ko'chasi, 2-uy",               phone: "+998 (76) 228-19-09", email: "j.muzrabot@sud.uz" },
    { name: "Oltinsoy tuman sudi",     address: "Oltinsoy tumani, Bo'ston maxallasi",                       phone: "+998 (76) 228-19-10", email: "j.oltinsoy@sud.uz" },
    { name: "Sariosiyo tuman sudi",    address: "Sariosiyo tumani, Mehr-shavqat ko'chasi",                  phone: "+998 (76) 228-19-11", email: "j.sariosiyo@sud.uz" },
    { name: "Sherobod tuman sudi",     address: "Sherobod tumani, Mustaqillik ko'chasi, 14-uy",             phone: "+998 (76) 228-19-13", email: "j.sherobod@sud.uz" },
    { name: "Uzun tuman sudi",         address: "Uzun tumani, Yangiro'zg'or mahallasi",                     phone: "+998 (76) 228-19-12", email: "j.uzun@sud.uz" },
    { name: "Angor tuman sudi",        address: "Angor tumani, At-Termiziy ko'chasi, 1-uy",                 phone: "+998 (76) 228-19-03", email: "j.angor@sud.uz" },
    { name: "Bandixon tuman sudi",     address: "Bandixon tumani, Guliston ko'chasi, 4-uy",                 phone: "+998 (76) 228-19-15", email: "j.bandixon@sud.uz" },
    { name: "Boysun tuman sudi",       address: "Boysun tumani, Olmazor ko'chasi",                          phone: "+998 (76) 228-19-04", email: "j.boysun@sud.uz" },
    { name: "Sho'rchi tuman sudi",     address: "Sho'rchi tuman, Mustaqillik ko'chasi, 115 uy",             phone: "+998 (76) 228-19-14", email: "j.shurchi@sud.uz" },
  ],
};

export function getCourts(type: CourtType, regionId: string): CourtEntry[] {
  if (type === "oliy") return [OLIY_SUD];
  // For fuq/mam/iqt - use jin data as they share buildings in most regions
  return JIN[regionId] ?? [];
}
