// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tma/Catalog.tsx": () => import("../components/mockups/tma/Catalog.tsx"),
  "./components/mockups/tma/Home.tsx": () => import("../components/mockups/tma/Home.tsx"),
  "./components/mockups/tma/Payment.tsx": () => import("../components/mockups/tma/Payment.tsx"),
  "./components/mockups/tma/Success.tsx": () => import("../components/mockups/tma/Success.tsx")
};
